# Generated by Django 4.0.1 on 2022-02-04 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='raiting',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
